<?php

import("@.Utils.Smtp");
import("@.Utils.CertificationAction");

include_once 'Conf/enum_config.php';
include_once 'Conf/define_config.php';
include_once 'Conf/authorization_config.php';


class GenFunc { 
 
public static function getTableByIdName($idName)

{

	$tableArr = array(

	"isp_id"=>"isps",
"idc_id"=>"idcs",
"contract_id"=>"contracts",
"rack_id"=>"racks",
"user_id"=>"users",
"switch_id"=>"switches",
"vm_id"=>"vm_servers",
"department_id"=>"departments:department",
"server_id"=>"servers",
"budget_id"=>"budgets:begin_year:begin_month",
"supplier_id"=>"suppliers",
"role_id"=>"roles",
"comp_id"=>"companies",
"group_id"=>"groups",
"request_id"=>"component_request",
"detail_id"=>"componets_detail",
"model_id"=>"componet_model",
"mr_id"=>"machine_request",
"machine_id"=>"machines_detial",
""=>"",

 
	);

	return $tableArr[$idName];


}

 
   
public static function getTableFieldTitle($idName) 
{ 
	$tableArr = GenFunc::getTableFieldBase( ); 
	return $tableArr[$idName]; 
}
 
 
public static function getTableFieldBase( )

{

	$tableArr = array(


 

		"tablename.yz_admin"=>"管理员表",
		"yz_admin.id"=>"id",
		"yz_admin.username"=>"用户名",
		"yz_admin.nickname"=>"昵称",
		"yz_admin.password"=>"密码",
		"yz_admin.salt"=>"密码盐",
		"yz_admin.avatar"=>"头像",
		"yz_admin.email"=>"电子邮箱",
		"yz_admin.mobile"=>"手机号码",
		"yz_admin.loginfailure"=>"unsigned",
		"yz_admin.logintime"=>"登录时间",
		"yz_admin.loginip"=>"登录ip",
		"yz_admin.createtime"=>"创建时间",
		"yz_admin.updatetime"=>"更新时间",
		"yz_admin.token"=>"session标识",
		"yz_admin.status"=>"状态",
		"tablename.yz_admin_log"=>"管理员日志表",
		"yz_admin_log.id"=>"id",
		"yz_admin_log.admin_id"=>"unsigned",
		"yz_admin_log.username"=>"管理员名字",
		"yz_admin_log.url"=>"操作页面",
		"yz_admin_log.title"=>"日志标题",
		"yz_admin_log.content"=>"内容",
		"yz_admin_log.ip"=>"ip",
		"yz_admin_log.useragent"=>"user-agent",
		"yz_admin_log.createtime"=>"操作时间",
		"tablename.yz_advert"=>"广告表",
		"yz_advert.id"=>"id",
		"yz_advert.mediaimage"=>"媒体文件",
		"yz_advert.url"=>"广告链接",
		"yz_advert.startdate"=>"开始日期",
		"yz_advert.enddate"=>"结束日期",
		"yz_advert.createtime"=>"创建时间",
		"yz_advert.updatetime"=>"更新时间",
		"yz_advert.deletetime"=>"删除时间",
		"yz_advert.weigh"=>"权重",
		"yz_advert.status"=>"状态",
		"tablename.yz_area"=>"地区表",
		"yz_area.id"=>"id",
		"yz_area.pid"=>"父id",
		"yz_area.shortname"=>"简称",
		"yz_area.name"=>"名称",
		"yz_area.mergename"=>"全称",
		"yz_area.level"=>"层级:1=省",
		"yz_area.pinyin"=>"拼音",
		"yz_area.code"=>"长途区号",
		"yz_area.zip"=>"邮编",
		"yz_area.first"=>"首字母",
		"yz_area.lng"=>"经度",
		"yz_area.lat"=>"纬度",
		"tablename.yz_attachment"=>"附件表",
		"yz_attachment.id"=>"id",
		"yz_attachment.category"=>"类别",
		"yz_attachment.admin_id"=>"unsigned",
		"yz_attachment.user_id"=>"unsigned",
		"yz_attachment.url"=>"物理路径",
		"yz_attachment.imagewidth"=>"宽度",
		"yz_attachment.imageheight"=>"高度",
		"yz_attachment.imagetype"=>"图片类型",
		"yz_attachment.imageframes"=>"unsigned",
		"yz_attachment.filename"=>"文件名称",
		"yz_attachment.filesize"=>"unsigned",
		"yz_attachment.mimetype"=>"mime类型",
		"yz_attachment.extparam"=>"透传数据",
		"yz_attachment.createtime"=>"创建日期",
		"yz_attachment.updatetime"=>"更新时间",
		"yz_attachment.uploadtime"=>"上传时间",
		"yz_attachment.storage"=>"存储位置",
		"yz_attachment.sha1"=>"文件",
		"tablename.yz_auth_group"=>"分组表",
		"yz_auth_group.id"=>"id",
		"yz_auth_group.pid"=>"unsigned",
		"yz_auth_group.name"=>"组名",
		"yz_auth_group.rules"=>"规则id",
		"yz_auth_group.createtime"=>"创建时间",
		"yz_auth_group.updatetime"=>"更新时间",
		"yz_auth_group.status"=>"状态",
		"tablename.yz_auth_group_access"=>"权限分组表",
		"yz_auth_group_access.uid"=>"unsigned",
		"yz_auth_group_access.group_id"=>"unsigned",
		"tablename.yz_auth_rule"=>"节点表",
		"yz_auth_rule.id"=>"id",
		"yz_auth_rule.type"=>"menu为菜单",
		"yz_auth_rule.pid"=>"unsigned",
		"yz_auth_rule.name"=>"规则名称",
		"yz_auth_rule.title"=>"规则名称",
		"yz_auth_rule.icon"=>"图标",
		"yz_auth_rule.url"=>"规则url",
		"yz_auth_rule.condition"=>"条件",
		"yz_auth_rule.remark"=>"备注",
		"yz_auth_rule.ismenu"=>"unsigned",
		"yz_auth_rule.menutype"=>"菜单类型",
		"yz_auth_rule.extend"=>"扩展属性",
		"yz_auth_rule.py"=>"拼音首字母",
		"yz_auth_rule.pinyin"=>"拼音",
		"yz_auth_rule.createtime"=>"创建时间",
		"yz_auth_rule.updatetime"=>"更新时间",
		"yz_auth_rule.weigh"=>"权重",
		"yz_auth_rule.status"=>"状态",
		"tablename.yz_category"=>"分类表",
		"yz_category.id"=>"id",
		"yz_category.pid"=>"unsigned",
		"yz_category.type"=>"栏目类型",
		"yz_category.name"=>"name",
		"yz_category.nickname"=>"nickname",
		"yz_category.flag"=>"flag",
		"yz_category.image"=>"图片",
		"yz_category.keywords"=>"关键字",
		"yz_category.description"=>"描述",
		"yz_category.diyname"=>"自定义名称",
		"yz_category.createtime"=>"创建时间",
		"yz_category.updatetime"=>"更新时间",
		"yz_category.weigh"=>"权重",
		"yz_category.status"=>"状态",
		"tablename.yz_command"=>"在线命令表",
		"yz_command.id"=>"id",
		"yz_command.type"=>"类型",
		"yz_command.params"=>"参数",
		"yz_command.command"=>"命令",
		"yz_command.content"=>"返回结果",
		"yz_command.executetime"=>"unsigned",
		"yz_command.createtime"=>"unsigned",
		"yz_command.updatetime"=>"unsigned",
		"yz_command.status"=>"状态",
		"tablename.yz_config"=>"系统配置",
		"yz_config.id"=>"id",
		"yz_config.name"=>"变量名",
		"yz_config.group"=>"分组",
		"yz_config.title"=>"变量标题",
		"yz_config.tip"=>"变量描述",
		"yz_config.type"=>"类型:string",
		"yz_config.visible"=>"可见条件",
		"yz_config.value"=>"变量值",
		"yz_config.content"=>"变量字典数据",
		"yz_config.rule"=>"验证规则",
		"yz_config.extend"=>"扩展属性",
		"yz_config.setting"=>"配置",
		"tablename.yz_ems"=>"邮箱验证码表",
		"yz_ems.id"=>"id",
		"yz_ems.event"=>"事件",
		"yz_ems.email"=>"邮箱",
		"yz_ems.code"=>"验证码",
		"yz_ems.times"=>"unsigned",
		"yz_ems.ip"=>"ip",
		"yz_ems.createtime"=>"创建时间",
		"tablename.yz_order"=>"订单列表",
		"yz_order.id"=>"id",
		"yz_order.user_id"=>"unsigned",
		"yz_order.store_id"=>"unsigned",
		"yz_order.p_id"=>"unsigned",
		"yz_order.order_no"=>"订单号",
		"yz_order.relaname"=>"姓名",
		"yz_order.mobile"=>"联系电话",
		"yz_order.state"=>"订单状态:1=未到店",
		"yz_order.bgstate"=>"报告获取状态:1=未获取",
		"yz_order.remarks"=>"订单备注",
		"yz_order.prerange"=>"预约时间",
		"yz_order.gotime"=>"到店时间",
		"yz_order.createtime"=>"下单时间",
		"yz_order.updatetime"=>"修改时间",
		"yz_order.deletetime"=>"删除时间",
		"tablename.yz_project"=>"项目表",
		"yz_project.id"=>"id",
		"yz_project.projects"=>"项目名称",
		"yz_project.price"=>"项目价格",
		"yz_project.pavatar"=>"项目封面",
		"yz_project.pexplain"=>"项目说明",
		"yz_project.plabeltags"=>"项目标签",
		"yz_project.pswitch"=>"项目状态",
		"yz_project.mfswitch"=>"限时免费状态",
		"yz_project.createtime"=>"添加时间",
		"yz_project.updatetime"=>"修改时间",
		"yz_project.deletetime"=>"删除时间",
		"tablename.yz_score_goods"=>"yz_score_goods",
		"yz_score_goods.id"=>"id",
		"yz_score_goods.goodsname"=>"goodsname",
		"yz_score_goods.score"=>"score",
		"tablename.yz_sms"=>"短信验证码表",
		"yz_sms.id"=>"id",
		"yz_sms.event"=>"事件",
		"yz_sms.mobile"=>"手机号",
		"yz_sms.code"=>"验证码",
		"yz_sms.times"=>"unsigned",
		"yz_sms.ip"=>"ip",
		"yz_sms.createtime"=>"unsigned",
		"tablename.yz_store"=>"门店",
		"yz_store.id"=>"id",
		"yz_store.storename"=>"门店名称",
		"yz_store.avatar"=>"门店头像",
		"yz_store.contacts"=>"联系人",
		"yz_store.mobile"=>"门店电话",
		"yz_store.worktimes"=>"营业时间",
		"yz_store.people"=>"unsigned",
		"yz_store.city"=>"门店地址",
		"yz_store.address"=>"详细地址",
		"yz_store.lng"=>"经度",
		"yz_store.lat"=>"纬度",
		"yz_store.scontent"=>"门店详情",
		"yz_store.weigh"=>"unsigned",
		"yz_store.createtime"=>"创建时间",
		"yz_store.updatetime"=>"更新时间",
		"yz_store.deletetime"=>"删除时间",
		"yz_store.switch"=>"是否营业",
		"yz_store.wxcode"=>"小程序二维码",
		"tablename.yz_test"=>"测试表",
		"yz_test.id"=>"id",
		"yz_test.user_id"=>"会员id",
		"yz_test.admin_id"=>"管理员id",
		"yz_test.category_id"=>"unsigned",
		"yz_test.category_ids"=>"分类id(多选)",
		"yz_test.tags"=>"标签",
		"yz_test.week"=>"星期(单选):monday=星期一",
		"yz_test.flag"=>"标志(多选):hot=热门",
		"yz_test.genderdata"=>"性别(单选):male=男",
		"yz_test.hobbydata"=>"爱好(多选):music=音乐",
		"yz_test.title"=>"标题",
		"yz_test.content"=>"内容",
		"yz_test.image"=>"图片",
		"yz_test.images"=>"图片组",
		"yz_test.attachfile"=>"附件",
		"yz_test.keywords"=>"关键字",
		"yz_test.description"=>"描述",
		"yz_test.city"=>"省市",
		"yz_test.json"=>"配置:key=名称",
		"yz_test.multiplejson"=>"二维数组:title=标题",
		"yz_test.price"=>"unsigned",
		"yz_test.views"=>"unsigned",
		"yz_test.workrange"=>"时间区间",
		"yz_test.startdate"=>"开始日期",
		"yz_test.activitytime"=>"活动时间(datetime)",
		"yz_test.year"=>"年",
		"yz_test.times"=>"时间",
		"yz_test.refreshtime"=>"刷新时间",
		"yz_test.createtime"=>"创建时间",
		"yz_test.updatetime"=>"更新时间",
		"yz_test.deletetime"=>"删除时间",
		"yz_test.weigh"=>"权重",
		"yz_test.switch"=>"开关",
		"yz_test.status"=>"状态",
		"yz_test.state"=>"状态值:0=禁用",
		"tablename.yz_user"=>"会员表",
		"yz_user.id"=>"id",
		"yz_user.group_id"=>"unsigned",
		"yz_user.username"=>"用户名",
		"yz_user.nickname"=>"昵称",
		"yz_user.openid"=>"微信openid",
		"yz_user.realname"=>"真实姓名",
		"yz_user.password"=>"密码",
		"yz_user.salt"=>"密码盐",
		"yz_user.session_key"=>"session_key",
		"yz_user.email"=>"电子邮箱",
		"yz_user.mobile"=>"手机号",
		"yz_user.card"=>"身份证号码",
		"yz_user.avatar"=>"头像",
		"yz_user.level"=>"unsigned",
		"yz_user.gender"=>"unsigned",
		"yz_user.birthday"=>"生日",
		"yz_user.bio"=>"格言",
		"yz_user.money"=>"余额",
		"yz_user.score"=>"积分",
		"yz_user.successions"=>"unsigned",
		"yz_user.maxsuccessions"=>"unsigned",
		"yz_user.prevtime"=>"上次登录时间",
		"yz_user.logintime"=>"登录时间",
		"yz_user.loginip"=>"登录ip",
		"yz_user.loginfailure"=>"unsigned",
		"yz_user.joinip"=>"加入ip",
		"yz_user.jointime"=>"加入时间",
		"yz_user.createtime"=>"创建时间",
		"yz_user.updatetime"=>"更新时间",
		"yz_user.token"=>"token",
		"yz_user.status"=>"状态",
		"yz_user.verification"=>"验证",
		"yz_user.istz"=>"是否团长",
		"yz_user.tzewm"=>"团长二维码",
		"yz_user.jscore"=>"团长积分",
		"yz_user.fid"=>"团长id",
		"yz_user.screatetime"=>"邀请注册时间",
		"tablename.yz_user_face"=>"扫脸数据表",
		"yz_user_face.id"=>"id",
		"yz_user_face.user_id"=>"unsigned",
		"yz_user_face.o_id"=>"订单id",
		"yz_user_face.store_id"=>"检测机构id",
		"yz_user_face.zzhdf"=>"综合得分",
		"yz_user_face.facedata"=>"扫脸数据",
		"yz_user_face.zmimg"=>"正面数据",
		"yz_user_face.cming"=>"侧面数据",
		"yz_user_face.nwlk"=>"45度照片",
		"yz_user_face.mobile"=>"手机号",
		"yz_user_face.nose"=>"鼻子数据",
		"yz_user_face.createtime"=>"上传时间",
		"yz_user_face.updatetime"=>"更新时间",
		"yz_user_face.status"=>"处理状态",
		"yz_user_face.obtainnum"=>"获取报告次数",
		"yz_user_face.sxzsbg"=>"展示人像图",
		"tablename.yz_user_group"=>"会员组表",
		"yz_user_group.id"=>"id",
		"yz_user_group.name"=>"组名",
		"yz_user_group.rules"=>"权限节点",
		"yz_user_group.createtime"=>"添加时间",
		"yz_user_group.updatetime"=>"更新时间",
		"yz_user_group.status"=>"状态",
		"tablename.yz_user_index"=>"小程序数据",
		"yz_user_index.id"=>"id",
		"yz_user_index.user_id"=>"会员id",
		"yz_user_index.jcnl"=>"检测年龄",
		"yz_user_index.index_bg"=>"首页图",
		"yz_user_index.xxfs"=>"首页形象分数",
		"yz_user_index.fsd"=>"肤色度",
		"yz_user_index.dhsm"=>"痘痕",
		"yz_user_index.zwsh"=>"皱纹",
		"yz_user_index.zhdf"=>"综合得分",
		"yz_user_index.zuigdf"=>"最高得分",
		"yz_user_index.zddf"=>"最低得分",
		"yz_user_index.pjdf"=>"平均得分",
		"yz_user_index.daybg"=>"档案页图像",
		"yz_user_index.zhjctime"=>"最后检测日期",
		"yz_user_index.uptime"=>"修改日期",
		"yz_user_index.kspf"=>"抗衰评分",
		"yz_user_index.store_id"=>"商家id",
		"yz_user_index.zmsy"=>"赞美话语",
		"tablename.yz_user_money_log"=>"会员余额变动表",
		"yz_user_money_log.id"=>"id",
		"yz_user_money_log.user_id"=>"unsigned",
		"yz_user_money_log.money"=>"变更余额",
		"yz_user_money_log.before"=>"变更前余额",
		"yz_user_money_log.after"=>"变更后余额",
		"yz_user_money_log.memo"=>"备注",
		"yz_user_money_log.createtime"=>"创建时间",
		"tablename.yz_user_rule"=>"会员规则表",
		"yz_user_rule.id"=>"id",
		"yz_user_rule.pid"=>"父id",
		"yz_user_rule.name"=>"名称",
		"yz_user_rule.title"=>"标题",
		"yz_user_rule.remark"=>"备注",
		"yz_user_rule.ismenu"=>"是否菜单",
		"yz_user_rule.createtime"=>"创建时间",
		"yz_user_rule.updatetime"=>"更新时间",
		"yz_user_rule.weigh"=>"权重",
		"yz_user_rule.status"=>"状态",
		"tablename.yz_user_score"=>"yz_user_score",
		"yz_user_score.id"=>"id",
		"yz_user_score.user_id"=>"user_id",
		"yz_user_score.fid"=>"fid",
		"yz_user_score.oid"=>"预约订单id",
		"yz_user_score.scoretype"=>"1是注册",
		"yz_user_score.createtime"=>"createtime",
		"yz_user_score.score"=>"score",
		"yz_user_score.isadd"=>"是否加积分",
		"yz_user_score.isqx"=>"是否取消：0否",
		"yz_user_score.nowscore"=>"nowscore",
		"tablename.yz_user_score_dh"=>"yz_user_score_dh",
		"yz_user_score_dh.id"=>"id",
		"yz_user_score_dh.user_id"=>"用户id",
		"yz_user_score_dh.score"=>"花费积分",
		"yz_user_score_dh.goodname"=>"兑换商品",
		"yz_user_score_dh.createtime"=>"添加时间",
		"yz_user_score_dh.updatetime"=>"审核时间",
		"yz_user_score_dh.state"=>"兑换状态:0=申请中",
		"tablename.yz_user_score_log"=>"会员积分变动表",
		"yz_user_score_log.id"=>"id",
		"yz_user_score_log.user_id"=>"unsigned",
		"yz_user_score_log.score"=>"变更积分",
		"yz_user_score_log.before"=>"变更前积分",
		"yz_user_score_log.after"=>"变更后积分",
		"yz_user_score_log.memo"=>"备注",
		"yz_user_score_log.createtime"=>"创建时间",
		"tablename.yz_user_score_rule"=>"积分规则表",
		"yz_user_score_rule.id"=>"id",
		"yz_user_score_rule.mintj"=>"最小提现金额",
		"yz_user_score_rule.scoremoney"=>"多少积分兑换1元",
		"yz_user_score_rule.dhinfo"=>"兑换说明",
		"yz_user_score_rule.scorezc"=>"注册赠送积分",
		"yz_user_score_rule.scoreyy"=>"预约赠送积分",
		"yz_user_score_rule.scoresl"=>"扫脸赠送积分",
		"yz_user_score_rule.txmey1"=>"选择金额1",
		"yz_user_score_rule.txmey2"=>"选择金额2",
		"yz_user_score_rule.txmey3"=>"选择金额3",
		"yz_user_score_rule.txmey4"=>"选择金额4",
		"yz_user_score_rule.txmey5"=>"选择金额5",
		"yz_user_score_rule.txmey6"=>"选择金额6",
		"tablename.yz_user_token"=>"会员token表",
		"yz_user_token.token"=>"token",
		"yz_user_token.user_id"=>"unsigned",
		"yz_user_token.createtime"=>"创建时间",
		"yz_user_token.expiretime"=>"过期时间",
		"tablename.yz_version"=>"版本表",
		"yz_version.id"=>"id",
		"yz_version.oldversion"=>"旧版本号",
		"yz_version.newversion"=>"新版本号",
		"yz_version.packagesize"=>"包大小",
		"yz_version.content"=>"升级内容",
		"yz_version.downloadurl"=>"下载地址",
		"yz_version.enforce"=>"unsigned",
		"yz_version.createtime"=>"创建时间",
		"yz_version.updatetime"=>"更新时间",
		"yz_version.weigh"=>"权重",
		"yz_version.status"=>"状态",
		
	"tablename.remote_file"=>"远端文件配置管理",
	"remote_file.id"=>"id",
	"remote_file.pname"=>"项目名",
	"remote_file.ip"=>"机器ip",
	"remote_file.path"=>"管理路径",
	"remote_file.c_type"=>"配置类型0:文件1:文件夹",
	"remote_file.m_type"=>"管理类型0:只读1:编辑",
	"remote_file.hosts"=>"多机同步配置",
	"remote_file.created_time"=>"记录创建时间",
	"remote_file.modified_time"=>"修改时间",
	"tablename.remote_file_log"=>"远端文件配置管理日志",
	"remote_file_log.id"=>"id",
	"remote_file_log.ip"=>"机器ip",
	"remote_file_log.path"=>"管理路径",
	"remote_file_log.log1"=>"变更前内容",
	"remote_file_log.log2"=>"变更后内容",
	"remote_file_log.created_time"=>"记录创建时间",
	"remote_file_log.modified_time"=>"修改时间",
	
	  
		"tablename.oss_fliter_egov"=>" oss_fliter_egov流量排行",
		"oss_fliter_egov.id"=>"id",
		"oss_fliter_egov.result_txt"=>"统计结果",
		"oss_fliter_egov.created_time"=>"创建时间",
		"oss_fliter_egov.modified_time"=>"修改时间",
		

		"tablename.sms_project"=>"短信任务项目",
		"sms_project.id"=>"id",
		"sms_project.stat_day"=>"开始日期",
		"sms_project.end_day"=>"结束日期",
		"sms_project.send_time"=>"短信发送时间",
		"sms_project.send_name"=>"短信任务名",
		"sms_project.send_content"=>"短信发送内容",
		"sms_project.send_phone"=>"短信接收人",
		"sms_project.send_mail"=>"邮件接收人",
		"sms_project.created_time"=>"记录创建时间",
		"sms_project.modified_time"=>"修改时间",
		"tablename.sms_sub"=>"短信子任务表",
		"sms_sub.id"=>"id",
		"sms_sub.send_day"=>"短信发送日期时间",
		"sms_sub.send_name"=>"短信任务名",
		"sms_sub.send_content"=>"短信发送内容",
		"sms_sub.send_phone"=>"短信接收人",
		"sms_sub.send_mail"=>"邮件接收人",
		"sms_sub.send_flag"=>"是否已发送",
		"sms_sub.created_time"=>"记录创建时间",
		"sms_sub.modified_time"=>"修改时间",
	  

		
		"tablename.mulu_link"=>"目录链",
		"mulu_link.id"=>"id",
		"mulu_link.data_time"=>"数据时间",
		"mulu_link.dept_name"=>"部门名称",
		"mulu_link.dept_code"=>"部门编码",
		"mulu_link.sys_id"=>"系统id",
		"mulu_link.sys_name"=>"系统名称",
		"mulu_link.created_time"=>"记录创建时间",
		"mulu_link.modified_time"=>"修改时间",
		"tablename.file_config"=>"配置文件管理项目",
		"file_config.id"=>"id",
		"file_config.name"=>"name",
		"file_config.file_path"=>"文件绝对路径",
		"file_config.file_desc"=>"配置说明",
		"file_config.created_time"=>"记录创建时间",
		"file_config.modified_time"=>"修改时间",
		"tablename.wh_project"=>"信创通州王恒机房项目",
		"wh_project.id"=>"id",
		"wh_project.project_name"=>"项目名",
		"wh_project.path"=>"转发路径(不带斜杠)",
		"wh_project.server_txt"=>"后台服务列表",
		"wh_project.created_time"=>"创建时间",
		"wh_project.modified_time"=>"修改时间",
		"tablename.wh_subtask"=>"信创通州王恒机房子任务",
		"wh_subtask.id"=>"id",
		"wh_subtask.project_id"=>"隶属项目",
		"wh_subtask.task_mark"=>"任务标记",
		"wh_subtask.task_stats"=>"任务状态",
		"wh_subtask.created_time"=>"创建时间",
		"wh_subtask.modified_time"=>"修改时间",
		
		
	"tablename.jd_project"=>"京东云mtgnotice项目",
	"jd_project.id"=>"id",
	"jd_project.project_name"=>"项目名",
	"jd_project.path"=>"转发路径(不带斜杠)",
	"jd_project.server_txt"=>"后台服务列表",
	"jd_project.created_time"=>"创建时间",
	"jd_project.modified_time"=>"修改时间",
	"tablename.jd_subtask"=>"京东云mtgnotice项目子任务",
	"jd_subtask.id"=>"id",
	"jd_subtask.project_id"=>"隶属项目",
	"jd_subtask.task_mark"=>"任务标记",
	"jd_subtask.task_stats"=>"任务状态",
	"jd_subtask.created_time"=>"创建时间",
	"jd_subtask.modified_time"=>"修改时间",
	"tablename.rg_project"=>"红绿灯项目",
	"rg_project.id"=>"id",
	"rg_project.name"=>"项目名",
	"rg_project.mark"=>"项目标记",
	"rg_project.memo"=>"项目备注",
	"rg_project.created_time"=>"记录创建时间",
	"rg_project.modified_time"=>"修改时间",
	"tablename.rg_sub"=>"红绿灯项目子灯",
	"rg_sub.id"=>"id",
	"rg_sub.mark"=>"红绿灯项目标记",
	"rg_sub.item_name"=>"监控子灯名",
	"rg_sub.item_mark"=>"监控子灯标记",
	"rg_sub.item_data"=>"子灯数据",
	"rg_sub.created_time"=>"记录创建时间",
	"rg_sub.modified_time"=>"修改时间",


		"tablename.king_monitor"=>"金山监控数据",
		"king_monitor.id"=>"id",
		"king_monitor.instance_id"=>"instance_id",
		"king_monitor.fixed_ip_address"=>"固定ip",
		"king_monitor.floating_ip_address"=>"浮动ip",
		"king_monitor.stat_time"=>"金山统计时间",
		"king_monitor.cpu_min_day"=>"cpu_min_day",
		"king_monitor.cpu_avg_day"=>"cpu_avg_day",
		"king_monitor.cpu_max_day"=>"cpu_max_day",
		"king_monitor.mem_min_day"=>"mem_min_day",
		"king_monitor.mem_avg_day"=>"mem_avg_day",
		"king_monitor.mem_max_day"=>"mem_max_day",
		"king_monitor.disk_min_day"=>"disk_min_day",
		"king_monitor.disk_avg_day"=>"disk_avg_day",
		"king_monitor.disk_max_day"=>"disk_max_day",
		"king_monitor.my_score"=>"资源使用率得分",
		"king_monitor.created_time"=>"记录创建时间",
		"king_monitor.modified_time"=>"修改时间",

		
	"tablename.xc_project"=>"信创项目",
	"xc_project.id"=>"id",
	"xc_project.project_name"=>"项目名",
	"xc_project.path"=>"转发路径(不带斜杠)",
	"xc_project.server_txt"=>"后台服务列表",
	"xc_project.created_time"=>"创建时间",
	"xc_project.modified_time"=>"修改时间",
	
	"tablename.xc_subtask"=>"信创项目子任务",
	"xc_subtask.id"=>"id",
	"xc_subtask.project_id"=>"隶属项目",
	"xc_subtask.task_mark"=>"任务标记",
	"xc_subtask.task_stats"=>"任务状态",
	"xc_subtask.created_time"=>"创建时间",
	"xc_subtask.modified_time"=>"修改时间",
	
	"tablename.year_guihua"=>"预算规划",
	"year_guihua.id"=>"id",
	"year_guihua.s_mode"=>"模块",
	"year_guihua.s_desc"=>"服务说明",
	"year_guihua.s_service"=>"服务",
	"year_guihua.base_ip"=>"锚定ip",
	"year_guihua.max_cpu"=>"cpu高峰期",
	"year_guihua.avg_cpu"=>"cpu平均",
	"year_guihua.max_memory"=>"内存高峰期",
	"year_guihua.avg_memory"=>"内存平均",
	"year_guihua.disk_usag"=>"磁盘使用率",
	"tablename.high_cpu_memory"=>"两周cpu内存峰值",
	"high_cpu_memory.id"=>"id",
	"high_cpu_memory.fixed_ip_address"=>"内网ip",
	"high_cpu_memory.high_cpu"=>"cpu峰值(百分率)",
	"high_cpu_memory.high_memory"=>"内存峰值(百分率)",
	"high_cpu_memory.other_desc"=>"归属人",
	"high_cpu_memory.created_time"=>"记录创建时间",
	"high_cpu_memory.modified_time"=>"修改时间",

	
		"tablename.list_assert"=>"分类预算表",
		"list_assert.id"=>"id",
		"list_assert.ywlb"=>"业务类别",
		"list_assert.display_name"=>"业务系统",
		"list_assert.real_hostname"=>"真实机器名",
		"list_assert.vcpus"=>"cpu",
		"list_assert.memory_mb"=>"内存",
		"list_assert.root_gb"=>"系统盘(g)",
		"list_assert.lowdisk"=>"普通数据盘",
		"list_assert.ssd_gb"=>"高性能数据盘(g)",
		"list_assert.localdisk"=>"本地盘",
		"list_assert.node_number"=>"机器数量",
		"list_assert.vcpus_high"=>"cpu两周峰值",
		"list_assert.memory_mb_high"=>"内存两周峰值",


		"tablename.xinchuang_machine"=>"信创资产",
		"xinchuang_machine.id"=>"id",
		"xinchuang_machine.useful"=>"虚拟机用途",
		"xinchuang_machine.os_version"=>"操作系统版本",
		"xinchuang_machine.in_area"=>"区域",
		"xinchuang_machine.cpu"=>"cpu(核)",
		"xinchuang_machine.memory"=>"内存(gb)",
		"xinchuang_machine.sys_disk"=>"系统盘(gb)",
		"xinchuang_machine.data_disk"=>"云硬盘(gb)",
		"xinchuang_machine.oss"=>"对象存储(gb)",
		"xinchuang_machine.zww_ip"=>"政务外网地址",
		"xinchuang_machine.in_ip"=>"云内网络地址",
		"xinchuang_machine.vip_ip"=>"集群vip地址",
		"xinchuang_machine.newpass"=>"newpass",
		"xinchuang_machine.my_group"=>"用途分类",
		"xinchuang_machine.my_service"=>"部署服务",
		"xinchuang_machine.my_host"=>"主机名",
		"xinchuang_machine.my_agent"=>"能访问互联网区代理",
		"xinchuang_machine.my_vpc"=>"所在vpc",
		"xinchuang_machine.created_time"=>"记录创建时间",
		"xinchuang_machine.modified_time"=>"修改时间",
		
		"tablename.resource_use"=>"资源使用率",
		"resource_use.id"=>"id",
		"resource_use.stat_time"=>"日期",
		"resource_use.my_title"=>"标题",
		"resource_use.my_content"=>"内容",
		"resource_use.resource_use"=>"资源使用率",
		"resource_use.del_flag"=>"逻辑删除标识",
		"resource_use.create_time"=>"创建时间",
		"resource_use.update_time"=>"修改时间",
		
	"tablename.jde_assert"=>"京东云互联网区资产",
	"jde_assert.id"=>"id",
	"jde_assert.instance_id"=>"资产id",
	"jde_assert.instance_name"=>"资产名",
	"jde_assert.region"=>"所在地区",
	"jde_assert.image_id"=>"镜像id",
	"jde_assert.image_name"=>"镜像名",
	"jde_assert.image_os"=>"镜像操作系统",
	"jde_assert.availability_zone"=>"可用区",
	"jde_assert.availability_group_id"=>"可用区分组id",
	"jde_assert.availability_group_name"=>"可用区分组名",
	"jde_assert.fault_domain"=>"故障域",
	"jde_assert.eip_address"=>"公网ip",
	"jde_assert.ipv6"=>"ipv6",
	"jde_assert.ipv4"=>"内网ip",
	"jde_assert.vpcid"=>"vpcid",
	"jde_assert.vpc_name"=>"vpc名",
	"jde_assert.subnet_id"=>"子网id",
	"jde_assert.subnet_name"=>"子网名",
	"jde_assert.m_status"=>"机器运行状态",
	"jde_assert.instance_type"=>"实例类型",
	"jde_assert.cpu"=>"cpu核数",
	"jde_assert.memory"=>"内存量",
	"jde_assert.bandwidth"=>"公网带宽",
	"jde_assert.tag"=>"标识",
	"jde_assert.dedicated_host_id"=>"以前的id",
	"jde_assert.dedicated_host_name"=>"以前的名字",
	"jde_assert.no_charges_for_stopped_instance"=>"停机计费情况",
	"jde_assert.billing_type"=>"计费类型",
	"jde_assert.creation_time"=>"机器创建时间",
	"jde_assert.expiration_time"=>"机器过期时间",
	"jde_assert.attach_cloud_disks"=>"关联云盘",
	"jde_assert.res_group_id"=>"资源组id",
	"jde_assert.res_group_name"=>"资源组名",
	"jde_assert.jde_account"=>"隶属京东云账号",
	"jde_assert.my_owner"=>"负责人",
	"jde_assert.my_project"=>"隶属项目",
	"jde_assert.my_service"=>"用途",
	"jde_assert.del_flag"=>"是否已删除",
	"jde_assert.created_time"=>"记录创建时间",
	"jde_assert.modified_time"=>"修改时间",
	
		
	"tablename.error_history"=>"历史故障处理",
	"error_history.id"=>"id",
	"error_history.cgroup"=>"所属环境",
	"error_history.error_log"=>"故障情况",
	"error_history.is_need"=>"是否需要处理",
	"error_history.doing_log"=>"处理方法",
	"error_history.future_log"=>"未来是否有隐患",
	"error_history.created_time"=>"记录创建时间",
	"error_history.modified_time"=>"修改时间",
		
	"tablename.third_alarm"=>"第三方应用报警列表",
	"third_alarm.id"=>"id",
	"third_alarm.stat_time"=>"报警时间",
	"third_alarm.report_txt"=>"报警报告",
	"third_alarm.created_time"=>"记录创建时间",
	"third_alarm.modified_time"=>"修改时间",
	
	"tablename.third_xunjian"=>"第三方应用巡检管理",
	"third_xunjian.id"=>"id",
	"third_xunjian.stat_time"=>"巡检时间",
	"third_xunjian.report_txt"=>"巡检报告",
	"third_xunjian.created_time"=>"记录创建时间",
	"third_xunjian.modified_time"=>"修改时间",
	
	"tablename.third_app"=>"第三方应用管理",
	"third_app.id"=>"id",
	"third_app.ak"=>"applicationkey",
	"third_app.name"=>"应用名",
	"third_app.deploymentenvironment"=>"部署环境",
	"third_app.icon"=>"图标",
	"third_app.my_description"=>"描述",
	"third_app.om_company"=>"开发公司",
	"third_app.pc_url"=>"pc端地址",
	"third_app.mobile_url"=>"移动端地址",
	"third_app.created_time"=>"记录创建时间",
	"third_app.modified_time"=>"修改时间",

		"tablename.third_ipwhite"=>"第三方应用监控报警白名单",
		"third_ipwhite.id"=>"id",
		"third_ipwhite.name"=>"相关应用名",
		"third_ipwhite.from_accesskey"=>"accesskey",
		"third_ipwhite.send_phone"=>"报警手机号",
		"third_ipwhite.send_mail"=>"报警邮箱",
		"third_ipwhite.created_time"=>"记录创建时间",
		"third_ipwhite.modified_time"=>"修改时间",
		
		
	"tablename.batch_pwd"=>"机器密码管理",
	"batch_pwd.id"=>"id",
	"batch_pwd.batch_name"=>"批次",
	"batch_pwd.src_txt"=>"录入基础数据",
	"batch_pwd.gen_txt"=>"密码种子文本",
	"batch_pwd.pwd_txt"=>"对外密码本",
	"batch_pwd.created_time"=>"记录创建时间",
	"batch_pwd.modified_time"=>"修改时间",
	
		"tablename.notice_date"=>"有期限资产",
		"notice_date.id"=>"id",
		"notice_date.name"=>"资产名",
		"notice_date.notice_time"=>"过期时间",
		"notice_date.my_owner"=>"使用人",
		"notice_date.send_phone"=>"提醒手机号",
		"notice_date.send_mail"=>"提醒邮箱",
		"notice_date.created_time"=>"记录创建时间",
		"notice_date.modified_time"=>"修改时间",
		
	"tablename.tpaas_pod"=>"tpaas_pod",
	"tpaas_pod.id"=>"id",
	"tpaas_pod.name"=>"podname",
	"tpaas_pod.name_space"=>"namespace",
	"tpaas_pod.ready"=>"ready状态",
	"tpaas_pod.status"=>"运行状态",
	"tpaas_pod.age"=>"存活时间",
	"tpaas_pod.ip"=>"宿主机ip",
	"tpaas_pod.node"=>"所在节点",
	"tpaas_pod.created_time"=>"记录创建时间",
	
	"tablename.app_statuser"=>"app用户统计",
	"app_statuser.id"=>"id",
	"app_statuser.stat_day"=>"统计日期",
	"app_statuser.application_id"=>"application_id",
	"app_statuser.application_key"=>"application_key",
	"app_statuser.app_name"=>"app_name",
	"app_statuser.user_count"=>"用户数量",
	"app_statuser.created_time"=>"记录创建时间",
	
	"tablename.app_statdata"=>"app统计",
	"app_statdata.id"=>"id",
	"app_statdata.stat_day"=>"统计日期",
	"app_statdata.ip"=>"来源ip",
	"app_statdata.appkey"=>"appkey",
	"app_statdata.count"=>"计数",
	"app_statdata.created_time"=>"记录创建时间",
		"tablename.nginx_apitime"=>"api超时统计",
		"nginx_apitime.id"=>"id",
		"nginx_apitime.stat_time"=>"统计日",
		"nginx_apitime.domain"=>"统计域名",
		"nginx_apitime.result_txt"=>"统计结果",
		"nginx_apitime.created_time"=>"创建时间",
		"nginx_apitime.modified_time"=>"修改时间",
		"tablename.jf_scanassert"=>"扫描资产清单",
		"jf_scanassert.id"=>"id",
		"jf_scanassert.catlog"=>"类别",
		"jf_scanassert.use_desc"=>"用途",
		"jf_scanassert.hostname"=>"hostname",
		"jf_scanassert.hostport"=>"服务端口",
		"jf_scanassert.cpu"=>"cpu",
		"jf_scanassert.mem"=>"内存",
		"jf_scanassert.sysdisk"=>"系统盘",
		"jf_scanassert.datadisk"=>"数据盘",
		"jf_scanassert.oprsys"=>"操作系统",
		"jf_scanassert.fixed_ip_address"=>"固定ip",
		"jf_scanassert.floating_ip_address"=>"浮动ip",
		"jf_scanassert.masterid"=>"宿主机id",
		"jf_scanassert.created_time"=>"创建时间",
		"jf_scanassert.modified_time"=>"修改时间",

		"tablename.nginx_api_stat"=>"api情况分析",
		"nginx_api_stat.id"=>"id",
		"nginx_api_stat.stat_time"=>"统计时间",
		"nginx_api_stat.stat_domain"=>"分析域名",
		"nginx_api_stat.api"=>"api地址",
		"nginx_api_stat.all_count"=>"数量",
		"nginx_api_stat.all_nginx"=>"nginx台数",
		"nginx_api_stat.respose_time"=>"平均响应",
		"nginx_api_stat.count_200"=>"响应成功200次数",
		"nginx_api_stat.count_fail"=>"非200次数",
		"nginx_api_stat.percent_200"=>"响应成功率",
		"nginx_api_stat.created_time"=>"创建时间",
		"nginx_api_stat.modified_time"=>"修改时间",
	"tablename.nginx_access"=>"nginx访问量",
	"nginx_access.id"=>"id",
	"nginx_access.access_file"=>"文件源",
	"nginx_access.stat_time"=>"统计时间",
	"nginx_access.count_num"=>"数据量",
	"nginx_access.created_time"=>"创建时间",
	"nginx_access.modified_time"=>"修改时间",
	
	 
	
	"tablename.report_fast"=>"业务上报巡检",
	"report_fast.id"=>"id",
	"report_fast.report_fast"=>"上报内容",
	"report_fast.created_time"=>"创建时间",
	"report_fast.modified_time"=>"修改时间",
	
		"tablename.group_count"=>"群统计数据表",
		"group_count.id"=>"id",
		"group_count.full_path"=>"全路径",
		"group_count.full_name"=>"全路径名",
		"group_count.path_level"=>"路径深度",
		"group_count.group_count"=>"群数量",
		"group_count.creator"=>"创建者",
		"group_count.created_time"=>"创建时间",

		
		"tablename.nginx_conf"=>"nginx配置管理表",
		"nginx_conf.id"=>"id",
		"nginx_conf.name"=>"nginx机器命名",
		"nginx_conf.ip"=>"nginx机器管理ip",
		"nginx_conf.created_time"=>"创建时间",
		"nginx_conf.modified_time"=>"修改时间",
		"tablename.nginx_conf_sub"=>"nginx配置变更子表",
		"nginx_conf_sub.id"=>"id",
		"nginx_conf_sub.name"=>"nginx机器命名",
		"nginx_conf_sub.ip"=>"nginx机器管理ip",
		"nginx_conf_sub.before_conf"=>"变更前配置",
		"nginx_conf_sub.after_conf"=>"变更后配置",
		"nginx_conf_sub.created_time"=>"创建时间",
		"nginx_conf_sub.modified_time"=>"修改时间",
		
		"tablename.sentry9log"=>"sentry项目9数据检索",
		"sentry9log.id"=>"id",
		"sentry9log.searchkey"=>"检索关键词",
		"sentry9log.status"=>"任务状态",
		"sentry9log.result_flag"=>"结果格式",
		"sentry9log.result"=>"检索结果",
		"sentry9log.created_time"=>"创建时间",
		"sentry9log.modified_time"=>"修改时间",

		
		"tablename.five_data"=>"五位一体数据表",
		"five_data.id"=>"id",
		"five_data.ip"=>"来路ip",
		"five_data.appid"=>"应用id",
		"five_data.stat_time"=>"统计时间",
		"five_data.region"=>"统计地域",
		"five_data.type"=>"数据分类",
		"five_data.stat_value"=>"统计结果",
		"five_data.created_time"=>"创建时间",
		"five_data.modified_time"=>"修改时间",
	"tablename.fastdata_verify"=>"快照数据审核表",
	"fastdata_verify.id"=>"id",
	"fastdata_verify.stat_date"=>"创建时间",
	"fastdata_verify.name"=>"文档名",
	"fastdata_verify.doc_status"=>"文档状态",
	"fastdata_verify.created_time"=>"创建时间",
	"fastdata_verify.modified_time"=>"修改时间",
	"tablename.operater_log"=>"操作日志",
	"operater_log.id"=>"id",
	"operater_log.op_class"=>"操作分类",
	"operater_log.op_table"=>"主操作表",
	"operater_log.op_id"=>"主操作id",
	"operater_log.op_login"=>"操作人",
	"operater_log.op_action"=>"实际操作",
	"operater_log.before_data"=>"操作前数据",
	"operater_log.after_data"=>"操作后数据",
	"operater_log.created_time"=>"创建时间",
	"operater_log.modified_time"=>"修改时间",
	
	"tablename.problem_solve"=>"故障处理表",
	"problem_solve.id"=>"id",
	"problem_solve.problem"=>"问题",
	"problem_solve.is_solve"=>"是否解决",
	"problem_solve.solve_people"=>"解决者",
	"problem_solve.mymemo"=>"备注",
	"problem_solve.created_time"=>"创建时间",
	"problem_solve.modified_time"=>"修改时间",

	
		"tablename.online_assert"=>"金山云资产表",
		"online_assert.id"=>"id",
		"online_assert.group_name"=>"机器分类",
		"online_assert.az_name"=>"所属区域",
		"online_assert.use_unit_name"=>"租户",
		"online_assert.display_name"=>"业务系统",
		"online_assert.host"=>"主机名",
		"online_assert.vcpus"=>"cpu",
		"online_assert.memory_mb"=>"内存",
		"online_assert.root_gb"=>"系统盘(g)",
		"online_assert.ssd_gb"=>"数据盘(g)",
		"online_assert.os_type"=>"操作系统",
		"online_assert.fixed_ip_address"=>"固定ip",
		"online_assert.floating_ip_address"=>"浮动ip",
		"online_assert.created_time"=>"创建时间",
		"online_assert.modified_time"=>"修改时间",

		"online_assert.ywlb"=>"业务类别",
		"online_assert.my_owner"=>"主机负责人",
		"online_assert.hostport"=>"服务端口",
		"online_assert.is_local"=>"是否本地盘",
		
		"tablename.ip_history"=>"ip创建记录",
		"ip_history.id"=>"id",
		"ip_history.ip"=>"ip",
		"ip_history.created_time"=>"创建时间",
		
		"tablename.user_role"=>"用户配置角色",
		"user_role.id"=>"id",
		"user_role.login"=>"login",
		"user_role.md5pass"=>"密码md5值",
		"user_role.memo"=>"备注",
		"user_role.role_mark"=>"角色控权字符串(多个以逗号分割)",
		"user_role.creator"=>"创建者",
		"user_role.created_time"=>"创建时间",
		"user_role.modified_time"=>"修改时间",
		
		"tablename.markdown_inspection"=>"每日巡检记录",
		"markdown_inspection.id"=>"id",
		"markdown_inspection.stat_date"=>"巡检日期",
		"markdown_inspection.name"=>"巡检名",
		"markdown_inspection.filepath"=>"markdown文件存储位置",
		"markdown_inspection.creator"=>"创建者",
		"markdown_inspection.created_time"=>"创建时间",
		"markdown_inspection.modified_time"=>"修改时间",
		
	"tablename.djqp_msglog"=>"点聚用户日志",
	"djqp_msglog.id"=>"id",
	"djqp_msglog.op_type"=>"操作类型",
	"djqp_msglog.post_msg"=>"发送消息内容",
	"djqp_msglog.return_msg"=>"回应消息内容",
	"djqp_msglog.created_time"=>"创建时间",
	"djqp_msglog.modified_time"=>"修改时间",

	
	"tablename.not_need_alarm"=>"报警黑名单",
"not_need_alarm.id"=>"id",
"not_need_alarm.ip"=>"ip",
"not_need_alarm.port"=>"端口",
"not_need_alarm.created_time"=>"创建时间",
"not_need_alarm.modified_time"=>"修改时间",

			"tablename.http_local"=>"http本地调试code工具",
"http_local.id"=>"id",
"http_local.name"=>"测试名称",
"http_local.url"=>"测试本地url地址",
"http_local.created_time"=>"创建时间",
"http_local.modified_time"=>"修改时间",

  
	"tablename.zyw_item_color"=>"颜色规则管理",
"zyw_item_color.id"=>"id",
"zyw_item_color.item_name"=>"报警项目名",
"zyw_item_color.item_mark"=>"报警标记",
"zyw_item_color.item_march"=>"比较规则",
"zyw_item_color.item_color"=>"选择对应颜色",
"zyw_item_color.creator"=>"创建者",
"zyw_item_color.created_time"=>"创建时间",
"zyw_item_color.modified_time"=>"修改时间",
"tablename.zyw_item_history"=>"实际报警记录",
"zyw_item_history.id"=>"id",
"zyw_item_history.machine"=>"报警机器",
"zyw_item_history.port"=>"报警端口",
"zyw_item_history.item_name"=>"报警项目名",
"zyw_item_history.item_mark"=>"报警标记",
"zyw_item_history.item_color"=>"报警颜色",
"zyw_item_history.item_content"=>"实际报警内容",
"zyw_item_history.creator"=>"创建者",
"zyw_item_history.created_time"=>"创建时间",
"zyw_item_history.modified_time"=>"修改时间",

	"tablename.zyw_project"=>"主业务管理表",
"zyw_project.id"=>"id",
"zyw_project.project_name"=>"主业务名",
"zyw_project.project_en"=>"主业务英文标识",
"zyw_project.project_desc"=>"主业务说明",
"zyw_project.creator"=>"创建者",
"zyw_project.created_time"=>"创建时间",
"zyw_project.modified_time"=>"修改时间",
"tablename.zyw_access"=>"主业务访问链管理",
"zyw_access.id"=>"id",
"zyw_access.project_id"=>"隶属主业务",
"zyw_access.project_name"=>"主业务名",
"zyw_access.domain_list"=>"域名列表",
"zyw_access.nginx_list"=>"前置机ip列表",
"zyw_access.front_list"=>"前端机器ip列表",
"zyw_access.back_list"=>"后端机器ip列表",
"zyw_access.middle_list"=>"非数据库中间件地址",
"zyw_access.db_list"=>"关联数据库列表",
"zyw_access.creator"=>"创建者",
"zyw_access.created_time"=>"创建时间",
"zyw_access.modified_time"=>"修改时间",
"tablename.zyw_dev"=>"主业务研发链管理",
"zyw_dev.id"=>"id",
"zyw_dev.project_id"=>"隶属主业务",
"zyw_dev.project_name"=>"主业务名",
"zyw_dev.dev_list"=>"研发负责人联系方式",
"zyw_dev.test_list"=>"测试负责人联系方式",
"zyw_dev.ops_list"=>"运维负责人联系方式",
"zyw_dev.creator"=>"创建者",
"zyw_dev.created_time"=>"创建时间",
"zyw_dev.modified_time"=>"修改时间",


			"tablename.qianpi_list"=>"待签批列表管理",
"qianpi_list.id"=>"id",
"qianpi_list.file_name"=>"文件名",
"qianpi_list.urlpath"=>"下载地址",
"qianpi_list.creator"=>"创建者",
"qianpi_list.created_time"=>"创建时间",
"qianpi_list.modified_time"=>"修改时间",
"tablename.qianpi_history"=>"签批历史文件",
"qianpi_history.id"=>"id",
"qianpi_history.file_name"=>"文件名",
"qianpi_history.urlpath"=>"下载地址",
"qianpi_history.creator"=>"创建者",
"qianpi_history.created_time"=>"创建时间",
"qianpi_history.modified_time"=>"修改时间",


			"tablename.jssdk_project"=>"通用调试工具",
"jssdk_project.id"=>"id",
"jssdk_project.project_name"=>"调试项目名",
"jssdk_project.project_en"=>"调试项目英文名",
"jssdk_project.vconsole_flag"=>"是否打开vconsole",
"jssdk_project.cookie_setting"=>"增加cookie",
"jssdk_project.localstorage"=>"增加localstorage参数",
"jssdk_project.sessionstorage"=>"增加sessionstorage参数",
"jssdk_project.js_part"=>"js调试模式代码",
"jssdk_project.html_part"=>"html调试模式代码",
"jssdk_project.creator"=>"创建者",
"jssdk_project.created_time"=>"创建时间",
"jssdk_project.modified_time"=>"修改时间",

			"tablename.self_code2app"=>"自研应用快速对接code表",
"self_code2app.id"=>"id",
"self_code2app.appname"=>"自研应用名",
"self_code2app.app_en"=>"自研应用英文名",
"self_code2app.uuid"=>"对接计算uuid",
"self_code2app.url"=>"应用接收code的页面",
"self_code2app.created_time"=>"创建时间",
"self_code2app.modified_time"=>"修改时间",
		
	"tablename.third_app_user"=>"通用第三方实际用户",
"third_app_user.id"=>"id",
"third_app_user.app_id"=>"第三方应用测试id",
"third_app_user.appname"=>"第三方应用名",
"third_app_user.open_user_id"=>"用户开放唯一标识",
"third_app_user.open_team_id"=>"用户团队唯一标识",
"third_app_user.dept_id"=>"用户部门唯一标识",
"third_app_user.created_time"=>"创建时间",
"third_app_user.modified_time"=>"修改时间",
"tablename.craw_warning"=>"抓取的预警数据",
"craw_warning.id"=>"id",
"craw_warning.app_id"=>"第三方应用测试id",
"craw_warning.appname"=>"第三方应用名",
"craw_warning.title"=>"标题",
"craw_warning.city"=>"城市",
"craw_warning.type"=>"信号类型",
"craw_warning.level"=>"信号级别",
"craw_warning.icon"=>"图标",
"craw_warning.publish_time"=>"发布时间",
"craw_warning.publish_content"=>"发布内容",
"craw_warning.publisher"=>"发布者",
"craw_warning.need_flag"=>"是否需要处理",
"craw_warning.is_flag"=>"是否已经处理",
"craw_warning.created_time"=>"创建时间",
"craw_warning.modified_time"=>"修改时间",
"tablename.gw_change"=>"中间件交互数据表",
"gw_change.id"=>"id",
"gw_change.app_id"=>"第三方应用测试id",
"gw_change.appname"=>"第三方应用名",
"gw_change.apipath"=>"调用的api路径",
"gw_change.http_way"=>"调用消息是get还是post",
"gw_change.request_id"=>"调用消息的uuid",
"gw_change.request_header"=>"请求头里面的字段信息",
"gw_change.request_body"=>"请求的内容字段信息",
"gw_change.gw_result"=>"网关程序返回的接收请求的情况",
"gw_change.created_at"=>"纪录创建时间",

			"tablename.html_test"=>"html代码测试表",
"html_test.id"=>"id",
"html_test.name"=>"测试名",
"html_test.code"=>"html代码",
"html_test.created_time"=>"创建时间",
"html_test.modified_time"=>"修改时间",
			"tablename.code_test"=>"通用代码测试表",
"code_test.id"=>"id",
"code_test.name"=>"测试名",
"code_test.code"=>"测试核心代码",
"code_test.created_time"=>"创建时间",
"code_test.modified_time"=>"修改时间",

			"tablename.third_sys"=>"第三方应用测试",
"third_sys.id"=>"id",
"third_sys.appname"=>"第三方应用名",
"third_sys.ak"=>"ak",
"third_sys.sk"=>"sk",
"third_sys.created_time"=>"创建时间",
"third_sys.modified_time"=>"修改时间",
"tablename.third_sys_user"=>"第三方应用用户",
"third_sys_user.id"=>"id",
"third_sys_user.sys_id"=>"第三方应用测试id",
"third_sys_user.appname"=>"第三方应用名",
"third_sys_user.open_user_id"=>"用户开放唯一标识",
"third_sys_user.open_team_id"=>"用户团队唯一标识",
"third_sys_user.dept_id"=>"用户部门唯一标识",
"third_sys_user.third_id"=>"京英大学用户id",
"third_sys_user.created_time"=>"创建时间",
"third_sys_user.modified_time"=>"修改时间",
			"tablename.hq_name_card"=>"员工姓名和工号",
"hq_name_card.id"=>"id",
"hq_name_card.name"=>"员工姓名",
"hq_name_card.staff_no"=>"员工工号",
"hq_name_card.creator"=>"创建者",
"hq_name_card.created_time"=>"创建时间",
"hq_name_card.modified_time"=>"修改时间",

		"tablename.jydx_token_info"=>"京英大学token",
"jydx_token_info.id"=>"id",
"jydx_token_info.jydx_token"=>"京东大学token",
"jydx_token_info.modified_time"=>"修改时间",
"jydx_token_info.created_time"=>"创建时间",

		"tablename.jydx_user"=>"京英大学用户映射",
"jydx_user.id"=>"id",
"jydx_user.open_user_id"=>"用户开放唯一标识",
"jydx_user.open_team_id"=>"用户团队唯一标识",
"jydx_user.dept_id"=>"用户部门唯一标识",
"jydx_user.third_id"=>"京英大学用户id",
"jydx_user.created_time"=>"创建时间",
"jydx_user.modified_time"=>"修改时间",

	"tablename.sys_dict"=>"sys_dict",
"sys_dict.id"=>"id",
"sys_dict.dict_type"=>"类型",
"sys_dict.dict_key"=>"dict_key",
"sys_dict.dict_value"=>"dict_value",
	"tablename.weather_updowndata"=>"升降旗数据",
"weather_updowndata.id"=>"id",
"weather_updowndata.time_ym"=>"年月",
"weather_updowndata.up_data"=>"升旗时间",
"weather_updowndata.down_data"=>"降旗时间",
"weather_updowndata.creator"=>"创建者",
"weather_updowndata.created_time"=>"创建时间",
"weather_updowndata.modified_time"=>"修改时间",

	"tablename.weather_data"=>"天气预报数据",
"weather_data.id"=>"id",
"weather_data.city"=>"所在城市",
"weather_data.time_ym"=>"年月",
"weather_data.weather_data"=>"具体数据",
"weather_data.creator"=>"创建者",
"weather_data.created_time"=>"创建时间",
"weather_data.modified_time"=>"修改时间",
	"tablename.cpxx_alarm"=>"用户提醒信息列表",
"cpxx_alarm.id"=>"id",
"cpxx_alarm.creator"=>"用户唯一标识",
"cpxx_alarm.plate"=>"用户车牌号",
"cpxx_alarm.mark_way"=>"提醒方式",
"cpxx_alarm.mark_date"=>"需要提醒的时间",
"cpxx_alarm.mark_flag"=>"是否已经提醒",
"cpxx_alarm.created_time"=>"创建时间",
"cpxx_alarm.modified_time"=>"修改时间",

 	"tablename.cpxx_holiday"=>"节假日表",
"cpxx_holiday.id"=>"id",
"cpxx_holiday.holiday"=>"假日日期",
"cpxx_holiday.holiday_type"=>"假日类型",
"cpxx_holiday.creator"=>"用户唯一标识",
"cpxx_holiday.created_time"=>"创建时间",
"cpxx_holiday.modified_time"=>"修改时间",
	"tablename.cpxx_limit"=>"每日车牌限行表",
"cpxx_limit.id"=>"id",
"cpxx_limit.limit_day"=>"针对日期",
"cpxx_limit.limit_last"=>"限行尾号",
"cpxx_limit.creator"=>"创建者",
"cpxx_limit.created_time"=>"创建时间",
"cpxx_limit.modified_time"=>"修改时间",
"tablename.cpxx_plate"=>"用户车牌",
"cpxx_plate.id"=>"id",
"cpxx_plate.plate"=>"用户车牌号",
"cpxx_plate.mark_flag"=>"是否需要提醒",
"cpxx_plate.mark_way"=>"提醒方式",
"cpxx_plate.creator"=>"用户唯一标识",
"cpxx_plate.created_time"=>"创建时间",
"cpxx_plate.modified_time"=>"修改时间",

  
	);

	return $tableArr ;


}

 
 /*
public static function getTFAuth($idName)

{

	$tableArr = array(

	"tablename.pushfiles"=>"2",
"pushfiles.id"=>"1",
"pushfiles.type"=>"1",
"pushfiles.filepath"=>"1",
"pushfiles.reason"=>"1",
"pushfiles.man"=>"1",
"pushfiles.opflag"=>"1",
"pushfiles.lockflag"=>"1",
"pushfiles.created_at"=>"1",
"pushfiles.updated_at"=>"1",
"pushfiles.user_id"=>"1",
"tablename.pushfilelog"=>"2",
"pushfilelog.id"=>"1",
"pushfilelog.taskid"=>"1",
"pushfilelog.log"=>"1",
"pushfilelog.getflag"=>"1",
"pushfilelog.created_at"=>"1",
"tablename.packages"=>"2",
"packages.id"=>"1",
"packages.reason"=>"1",
"packages.user_id"=>"1",
"packages.opflag"=>"1",
"packages.lockflag"=>"1",
"packages.created_at"=>"1",
"packages.updated_at"=>"1",
"tablename.paklog"=>"2",
"paklog.id"=>"1",
"paklog.taskid"=>"1",
"paklog.log"=>"1",
"paklog.getflag"=>"1",
"paklog.created_at"=>"1",
"tablename.roles"=>"2",
"roles.id"=>"1",
"roles.rolename"=>"1",
"roles.roleauth"=>"1",
"roles.memo"=>"1",
"roles.created_at"=>"1",
"roles.updated_at"=>"1",
"tablename.users"=>"2",
"users.id"=>"1",
"users.role_id"=>"1",
"users.login"=>"1",
"users.zh_name"=>"1",
"users.email"=>"1",
"users.phone"=>"1",
"users.reporting"=>"1",
"users.created_at"=>"1",
"users.updated_at"=>"1",
"tablename.oplogs"=>"2",
"oplogs.id"=>"1",
"oplogs.user_id"=>"1",
"oplogs.ops_table"=>"1",
"oplogs.table_id"=>"1",
"oplogs.ops_sql"=>"1",
"oplogs.before_ops"=>"1",
"oplogs.after_ops"=>"1",

  
	);

	return $tableArr[$idName];


}

*/
 
 
public static function getTFAuthBase( )

{

	$tableArr = array(

	"tablename.pushfiles"=>"2",
"pushfiles.id"=>"1",
"pushfiles.type"=>"1",
"pushfiles.filepath"=>"1",
"pushfiles.reason"=>"1",
"pushfiles.man"=>"1",
"pushfiles.opflag"=>"1",
"pushfiles.lockflag"=>"1",
"pushfiles.created_at"=>"1",
"pushfiles.updated_at"=>"1",
"pushfiles.user_id"=>"1",
"tablename.pushfilelog"=>"2",
"pushfilelog.id"=>"1",
"pushfilelog.taskid"=>"1",
"pushfilelog.log"=>"1",
"pushfilelog.getflag"=>"1",
"pushfilelog.created_at"=>"1",
"tablename.packages"=>"2",
"packages.id"=>"1",
"packages.reason"=>"1",
"packages.user_id"=>"1",
"packages.opflag"=>"1",
"packages.lockflag"=>"1",
"packages.created_at"=>"1",
"packages.updated_at"=>"1",
"tablename.paklog"=>"2",
"paklog.id"=>"1",
"paklog.taskid"=>"1",
"paklog.log"=>"1",
"paklog.getflag"=>"1",
"paklog.created_at"=>"1",
"tablename.roles"=>"2",
"roles.id"=>"1",
"roles.rolename"=>"1",
"roles.roleauth"=>"1",
"roles.memo"=>"1",
"roles.created_at"=>"1",
"roles.updated_at"=>"1",
"tablename.users"=>"2",
"users.id"=>"1",
"users.role_id"=>"1",
"users.login"=>"1",
"users.zh_name"=>"1",
"users.email"=>"1",
"users.phone"=>"1",
"users.reporting"=>"1",
"users.created_at"=>"1",
"users.updated_at"=>"1",
"tablename.oplogs"=>"2",
"oplogs.id"=>"1",
"oplogs.user_id"=>"1",
"oplogs.ops_table"=>"1",
"oplogs.table_id"=>"1",
"oplogs.ops_sql"=>"1",
"oplogs.before_ops"=>"1",
"oplogs.after_ops"=>"1",

  
	);

	return $tableArr ;


}


}